spring.application.name=pokemon-card-back

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_card_db
spring.datasource.username=nightfury
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA - open-in-view 경고 제거
spring.jpa.open-in-view=false

# Server
server.port=8080

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
